---
title: "13C MFA: background"
resource_path: ["../"]
author: "Teddy Groves and Te Chen"
bibliography: bibliography.bib
reference-location: margin
format:
  html: default
  pdf: default
---

This document contains summaries of relevant papers relating to 13C metabolic flux analysis.

# Elementary Metabolite Units (EMU): a novel framework for modeling isotopic distributions

Reference: @antoniewiczElementaryMetaboliteUnits2007

This paper introduces the EMU method for solving the forward MFA problem (i.e.
finding the mass isotopomer distributions for a given set of fluxes).

# Viktor and Matthias's incawrapper package

[This
notebook](https://github.com/biosustain/incawrapper/blob/main/docs/examples/Published_data_examples_C_necator.ipynb)
has data and processing for a typical MFA problem. [The
repository](https://github.com/biosustain/incawrapper/) also has a lot of other
datasets and useful information and code.

# Understanding metabolism with flux analysis: From theory to application

Reference: @daiUnderstandingMetabolismFlux2017

This is a review paper covering metabolic flux analysis in general.

# Input data for a 13C MFA experiment

Input data consists of:

* A description of the metabolic network, including:

  * Stoichiometric coefficient of each compound in each reaction

  * Atom transitions of each reaction, i.e. given the arrangement of labellable
  atoms on one side of the reaction, what is the arrangement on the other side.

* Description of the labelled compounds added to the experiments, or "tracers".
i.e. a list including the following information for each tracer:

  * compound id

  * positions of labelled atoms

  * purity, i.e. for each position, the proportion of atoms in that position
  that were labelled

* Specification of which tracers were used in which experiments, and with what
enrichment level (i.e. what proportion of each tracer's compound was the
tracer.)

* Direct flux measurements, i.e. ones that did not require labelling. For each measurement:

  * reaction id
  * experiment id
  * measured flux
  * measurement error

* Mass isotopomer distribution measurements. For each measurement:

  * experiment id
  * compound id
  * fragment id
  * mass isotopomer id (i.e. 0, 1, 2, ...)
  * measured intensity (i.e. proportion of total fragment intensity)

# EnzymeMap

<https://chemrxiv.org/engage/chemrxiv/article-details/64ef093e79853bbd78ba04e5>

A Python package with a database of atom maps

Abstract:

> Enzymatic reactions are an ecofriendly, selective and versatile addition,
> sometimes even alternative to organic reactions for the synthesis of chemical
> compounds such as pharmaceuticals or fine chemicals. To identify suitable
> reactions, computational models to predict the activity of enzymes on
> non-native substrates, to perform retrosynthetic pathway searches, or to
> predict the outcomes of reactions including regio- and stereoselectivity are
> becoming increasingly important. However, current approaches are
> substantially hindered by the limited amount of available data, especially if
> balanced and atom mapped reactions are needed and if the models feature
> machine learning components. We therefore constructed a high-quality dataset
> (EnzymeMap) by developing a large set of correction and validation algorithms
> for recorded reactions in the literature and showcase its significant
> positive impact on machine learning models of retrosynthesis, forward
> prediction, and regioselectivity prediction, outperforming previous
> approaches by a large margin. Our dataset allows for deep learning models of
> enzymatic reactions with unprecedented accuracy, and is freely available
> online.
