---
title: "CMFA"
resource_path: ["../"]
subtitle: "Compositional Metabolic Flux Analysis"
author:
  - name: Teddy Groves
  - name: Te Chen
bibliography: bibliography.bib
reference-location: margin
format:
  html: default
  pdf: default
abstract: |
  13C Metabolic flux analysis [@wiechert13CMetabolicFlux2001] aims to infer the
  values of metabolic fluxes from the results of isotope labelling experiments
  using linear regression. This paper proposes a new measurement model for use in
  13C MFA that takes into account compositionality and demonstrates this model's
  use in the context of a new software application. We show that previous MFA
  approaches that do not take into account compositionality produce misleading or
  incomplete results in an illustrative case, whereas our method performs well.
---

# Introduction

## Isotopes, isotopomers and mass isotopomers

Isotopes are atoms whose nuclei have the same number of protons but different
numbers of neutrons. Isotopes instantiate the same element and have very
similar chemical properties, but have different atomic masses and physical
properties. For example, Carbon has three naturally occurring isotopes: 12C, 13C
and 14C, with respective atomic masses 12, 13 and 14. 14C occurs in negligible
quantities, and the natural ratio of 12C to 13C is known, making carbon suitable
for isotope labelling experiments where 12C is artificially replaced with 13C.

Isotopomers are forms of a compound that differ only by substitution of
isotopes. For example, [1-13C] glucose, [U-13C] glucose and [2-13C] glucose are
isotopomers that differ only in the isotopes of the carbon atoms in positions
1 and 2. In general, for a compound with $A$ occurrences of an atom with $I$
isotopes, there are $I^A$ corresponding isotopomers. For example, glucose has
six carbon atoms: assuming only 12C and 13C isotopes are present, there are
$2^6$ carbon isotopomers.

A mass isotopomer is an equivalence class of isotopomers that share the same
atomic mass. For example, [1-13C] glucose and [2-13C] glucose each have five
12C atoms and one 13C atom and therefore belong to the glucose mass isotopomer
$M_1$ with atomic mass 181.15 g/mol. Mass isotopomers are important because
measurements can often distinguish between mass isotopomers, but not between
isotopomers with the same atomic mass.

## Labelling experiments

In a labelling experiment, an organism is fed on feedstock with a known
isotopomer distribution. Depending on the prevailing metabolic fluxes,
the labelled and unlabelled isotopomers will propagate differently through
the organism. In particular, the organism will sometimes reach a metabolic
and isotopic steady state, so that neither the concentrations of internal
metabolites nor the distributions of each metabolite's isotopomers change
over time. In this work we consider labelling experiments where the relative
concentrations of mass iosopomers of some compounds in a metabolic network are
measured at metabolic and isotopic steady state.

The relative mass isotopomer distribution for a compound with $k$ mass
isotopomers is a vector $v\in\Delta^k$, where $\Delta^k$ is the $k$-simplex. A
measurement of this quantity is another simplex vector $y\in\Delta^k$.

For example, XXX.

## 13C Metabolic Flux Analysis

13C metabolic flux analysis considers a known metabolic network consisting of
$M$ compounds and $N$ reactions with stoichiometric coefficients $S\in\mathbb{R}
^{M\times N}$ representing the amount of each compound consumed and produced
by each reaction, plus an atom transition map for each reaction.

The atom transition map for a reaction specifies in what order the
potentially-labelled atoms occur in each of the reaction's products, compared
with their order among the reaction's substrates. For example, consider the
reaction $A + B \rightarrow C + 2D$. An atom transition map for this reaction
could have the form $A_{abcd} + B_{ef} \rightarrow C + D_{bdc} + D_{efa}$,
indicating that the reaction produces a molecule of compound $C$ with no
labelled atoms and two molecules of compound $D$, one of which jumbles the order
of the last three labellable atoms of compound $A$, while the other preserves
the order of compound $B$'s labellable atoms and adds compound $A$'s first atom
on the end.

The remaining input for 13C MFA is as follows:

- Known isotope proportions for some compounds, typically the feed.

- Measured fluxes for some reactions, possibly with known measurement error.

- Measured mass isotopomer proportions for some compounds, possibly with known
measurement error.

The task of inferring the label pattern corresponding to a known flux assignment
is known as the "forward problem". [REFERENCE] shows how, given the input
information described above, assumptions of metabolic and isotopic steady state
and a known flux for each reaction, it is possible to calculate the isotopomer
distribution for each compound in a network.

Unfortunately, solving the forward problem in terms of isotopomers is of
limited use for real applications due to the prohibitively large number
of isotopomers that need to be considered. As a result of this difficulty
there has been considerable interest in more concise representations of
the forward problem [REFERNECES]. Below [INTERNAL REFERENCE] we consider
in detail the "elementary metabolite unit" representation introduced in
@antoniewiczElementaryMetaboliteUnits2007.

The inverse problem of inferring steady state fluxes from measured mass
isotopomer distributions can be solved using a statistical model that links
these measurements with latent parameters representing flux configurations.
In general, such a model specifies the probability density $p(y\mid v)$ of the
measurement $y$ given a true flux assignment $v$. Typically a linear model is
used, so that the probability density is given by

$$
p(y\mid v) = N(y\mid r(v), \Sigma)
$$

where $r(v)$ is the mass isotopomer distribution corresponding to $v$,
calculated by solving the forward problem, and $\Sigma$ is a covariance matrix
representing the error in the measurement apparatus.

## The Elementary Metabolite Unit representation

## Compositional Regression

Compositional data is data that is subject to a unit-sum constraint. For
example, a compositional dataset might record the amount of fat, protein and
other ingredients in some blocks of butter as proportions of the total mass of
each block. These proportions are constrained to sum to exactly one.

It is well known that, in general, applying non-compositional data
analysis methods to compositional data is dangerous because these
methods can easily misinterpret constraint-induced correlations
[@aitchisonjStatisticalAnalysisCompositional, Ch. 3].

Compositional regression methods employ constrained measurement distributions
to analyse compositional data, allowing induced correlations to be accounted
for naturally. Examples of such distributions include the logistic-normal and
Dirichlet distributions [@aitchisonjStatisticalAnalysisCompositional, Ch. 3]
among others.

Compositional regression methods are appropriate for 13C MFA because mass
isotopomer distributions and their measurements are subject to unit-sum
constraints. We therefore considered it likely that the standard practice of
applying non-compositional statistical analysis to such data would produce
incorrect results.

## Existing solutions

Existing implementations of 13C MFA include:

- INCA
- 13CFLUX2
- Metran
- OpenFlux(2)
- FluxPyt
- mfapy
- Sysmetab
- iso2flux
- Flux-P
- WUFlux
- OpenMebius
- influx\_s

See @daiUnderstandingMetabolismFlux2017, @falcoMetabolicFluxAnalysis2022 for
reviews of available software implementing 13C MFA. We wish to note several
limitations of the currently available software:

- There is no previous implementation of compositional regression analysis in
the context of 13C MFA; all previous implementations apply a linear model either
explicitly as in [@theorellBeCertainUncertainty2017, Eq. 3] or more commonly
implicitly through the use of least-squares optimisation.
- The only software implementing Bayesian 13C MFA is proprietary.

# Methods

## Statistical model
## Software implementation

# Results

## Case study: toy model
## Case study: compositional vs non-compositional
## Case study: real data

# Discussion

## Recommendations
## Limitations

# References
